apiVersion: apps/v1
kind: Deployment
metadata:
  name: okosdoboz-shell
  labels:
    app.kubernetes.io/name: okosdoboz-shell
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: okosdoboz-shell
  template:
    metadata:
      labels:
        app.kubernetes.io/name: okosdoboz-shell
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: shell
          image: cr.hvg.hu/os/okosdoboz-shell:poc
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 500m
              memory: 128Mi
          startupProbe:
            httpGet:
              path: /shell-config.json
              port: http
            periodSeconds: 2
            timeoutSeconds: 2
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /shell-config.json
              port: http
            periodSeconds: 5
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /shell-config.json
              port: http
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3